data = {
    "El gallo": 1,
    "El diablito": 2,
    "La dama": 3,
    "El catrin": 4,
    "El paraguas": 5,
    "La sirena": 6,
    "La escalera": 7,
    "La botella": 8,
    "El barril": 9,
    "El arbol": 10,
    "El melon": 11,
    "El valiente": 12,
    "El gorrito": 13,
    "La muerte": 14,
    "La pera": 15,
    "La bandera": 16,
    "El bandolon": 17,
    "El violoncello": 18,
    "La garza": 19,
    "El pajaro": 20,
    "La mano": 21,
    "La bota": 22,
    "La luna": 23,
    "El cotorro": 24,
    "El borracho": 25,
    "El negrito": 26,
    "El corazon": 27,
    "La sandia": 28,
    "El tambor": 29,
    "El camarón": 30,
    "Las jaras": 31,
    "El músico": 32,
    "La araña": 33,
    "El soldado": 34,
    "La estrella": 35,
    "El cazo": 36,
    "El mundo": 37,
    "El apache": 38,
    "El nopal": 39,
    "El alacrán": 40,
    "La rosa": 41,
    "La calavera": 42,
    "La campana": 43,
    "El cantarito": 44,
    "El venado": 45,
    "El sol": 46,
    "La corona": 47,
    "La chalupa": 48,
    "El pino": 49,
    "El pescado": 50,
    "La palma": 51,
    "La maceta": 52,
    "El arpa": 53,
    "La rana": 54
}


def getFigureName(id: int):
    for key, value in data.items():
        if value == id:
            return key
    return "No existe"
